ccflags-y += -I$(src)			# needed for trace events

obj-$(CONFIG_ANDROID_TIMED_OUTPUT)	+= timed_output.o
obj-$(CONFIG_ANDROID_TIMED_GPIO)	+= timed_gpio.o rk_timed_gpio.o
obj-$(CONFIG_ASHMEM)			+= ashmem.o
